name: Build, test and validate (reusable workflow)

on:
  workflow_call:
    inputs:
      gradle-options:
        type: string
        description: "Any extra options to be passed to gradle"
        required: false
        default: ""

      os:
        type: string
        description: "OS to run on."
        required: true
        default: "ubuntu-latest"

      jdk-version:
        type: string
        required: true
        description: "JDK version to use." 

      run-tests:
        description: "Run tests"
        type: boolean
        default: true

jobs:
  build-and-test:
    name: test and assemble (JDK ${{ inputs.jdk-version }} on ${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: 30

    env:
      CI: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: actions/setup-node@v4
        with:
          node-version: 19

      - name: Install HiQLT CLI
        run: npm install --no-save qlt-cli@1.0.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Tests and assembly
        run: ./gradlew test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: all-test-outputs-jdk${{ inputs.jdk-version }}-os${{ inputs.os }}
          path: '**/TEST-*.xml'

      - name: Submit to HiQLT
        if: always()
        run: |
          npx qlt-cli qlt-upload -p "**/TEST-*.xml'" -s ${{ secrets.HIQLT_TOKEN }} -t carrot2 -e may-28-853pm -u https://gateway.hiqlt.com 

      - name: Store failed test outputs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-outputs-jdk${{ inputs.jdk-version }}-os${{ inputs.os }}
          path: '**/OUTPUT-*.txt'
